name: Tor Proxy Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      tor-proxy:
        image: dperson/torproxy
        ports:
          - 8118:8118
        options: >-
          --name proxy
    
    steps: 
    - name: Configure Tor
      run: |
        docker exec -it 10 bash -c "printf 'ControlPort 9051\nCookieAuthentication 1\nStrictNodes 1\nExitNodes {il}' > /etc/tor/torrc"

    - name: Restart tor
      run: |
        docker restart proxy
        timeout 75s sh -c 'until docker ps | grep proxy | grep -q healthy; do echo "Waiting for container to be healthy..."; sleep 5; done'
      
    - name: Run regular wtfismyip
      run: curl https://wtfismyip.com/json
      
    - name: Run proxified wtfismyip
      run: curl -Lx http://localhost:8118 https://wtfismyip.com/json
