name: Tor Proxy Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      proxy-vpn:
        image: ghcr.io/tal-sitton/proxy-vpn:latest
        ports:
          - 8118:8118
        options: >-
          --name proxy
          --privileged
          
    steps:
      - name: Run regular wtfismyip
        run: curl https://wtfismyip.com/json
      
      - name: Run proxified wtfismyip
        run: curl -Lx http://localhost:8118 https://wtfismyip.com/json
