name: Tor Proxy Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      proxy-vpn:
        image: ghcr.io/tal-sitton/proxy-vpn
        ports:
          - 8118:8118
        env:
          PASTE_DEV_KEY: ${{ secrets.PASTE_DEV_KEY }}
          PASTE_USER_KEY: ${{ secrets.PASTE_USER_KEY }}
        options: >-
          --name proxy
          --privileged
          
    steps:
      - name: Run regular wtfismyip
        run: curl https://wtfismyip.com/json
      
      - name: Run proxified wtfismyip
        run: curl -Lx http://localhost:8118 https://wtfismyip.com/json
